[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.18"
via_ir = true
optimizer = true
optimizer_runs = 10
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@solmate/=lib/solmate/src/',
]

[rpc_endpoints]
# mainnets
plg = "https://polygon-bor.publicnode.com"
# testnets
mumbai = "https://polygon-mumbai-bor.publicnode.com"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
